const level1 = new Level(
  [new Blob(), new Blob(), new Blob(), new Blob()],
  [new Cloud(), new Cloud()],
  [
    new BackgroundObject("./img/environment/background/sky.png", -320, 0),
    new BackgroundObject("./img/environment/background/background-clouds2.png", -320, 20),
    new BackgroundObject("./img/environment/background/background-clouds1.png", -320, 20),
    new BackgroundObject("./img/environment/background/mountains2.png", -320, 20),
    new BackgroundObject("./img/environment/background/mountains1.png", -320, 20),
    new BackgroundObject("./img/environment/background/ground1.png", -320, 20),
    new BackgroundObject("./img/environment/background/sky.png", 0, 0),
    new BackgroundObject("./img/environment/background/background-clouds2.png", 0, 20),
    new BackgroundObject("./img/environment/background/background-clouds1.png", 0, 20),
    new BackgroundObject("./img/environment/background/mountains2.png", 0, 20),
    new BackgroundObject("./img/environment/background/mountains1.png", 0, 20),
    new BackgroundObject("./img/environment/background/ground1.png", 0, 20),
    new BackgroundObject("./img/environment/background/sky.png", 320, 0),
    new BackgroundObject("./img/environment/background/background-clouds2.png", 320, 20),
    new BackgroundObject("./img/environment/background/background-clouds1.png", 320, 20),
    new BackgroundObject("./img/environment/background/mountains2.png", 320, 20),
    new BackgroundObject("./img/environment/background/mountains1.png", 320, 20),
    new BackgroundObject("./img/environment/background/ground1.png", 320, 20),
    new BackgroundObject("./img/environment/background/sky.png", 320 * 2, 0),
    new BackgroundObject("./img/environment/background/background-clouds2.png", 320 * 2, 20),
    new BackgroundObject("./img/environment/background/background-clouds1.png", 320 * 2, 20),
    new BackgroundObject("./img/environment/background/mountains2.png", 320 * 2, 20),
    new BackgroundObject("./img/environment/background/mountains1.png", 320 * 2, 20),
    new BackgroundObject("./img/environment/background/ground1.png", 320 * 2, 20),
  ]
);
