const level1 = new Level(
  [new Blobmaster(), new Blob(), new Blob(), new Blob(), new Blob()],
  [new Cloud(), new Cloud(), new Cloud(), new Cloud(), new Cloud(), new Cloud(), new Cloud(), new Cloud()],
  [
    new BackgroundObject("./img/environment/background/sky.png", -320, 0),
    new BackgroundObject("./img/environment/background/background-clouds2.png", -320, 20),
    new BackgroundObject("./img/environment/background/background-clouds1.png", -320, 20),
    new BackgroundObject("./img/environment/background/mountains2.png", -320, 20),
    new BackgroundObject("./img/environment/background/mountains1.png", -320, 20),
    new BackgroundObject("./img/environment/background/ground2.png", -320, 20),
    new BackgroundObject("./img/environment/background/ground_new.png", -320, 20),
    new BackgroundObject("./img/environment/background/foreground2.png", -320, 25),

    new BackgroundObject("./img/environment/background/sky.png", 0, 0),
    new BackgroundObject("./img/environment/background/background-clouds2.png", 0, 20),
    new BackgroundObject("./img/environment/background/background-clouds1.png", 0, 20),
    new BackgroundObject("./img/environment/background/mountains2.png", 0, 20),
    new BackgroundObject("./img/environment/background/mountains1.png", 0, 20),
    new BackgroundObject("./img/environment/background/ground2.png", 0, 20),
    new BackgroundObject("./img/environment/background/ground_new.png", 0, 20),
    new BackgroundObject("./img/environment/background/foreground2.png", 0, 25),

    new BackgroundObject("./img/environment/background/sky.png", 320, 0),
    new BackgroundObject("./img/environment/background/background-clouds2.png", 320, 20),
    new BackgroundObject("./img/environment/background/background-clouds1.png", 320, 20),
    new BackgroundObject("./img/environment/background/mountains2.png", 320, 20),
    new BackgroundObject("./img/environment/background/mountains1.png", 320, 20),
    new BackgroundObject("./img/environment/background/ground2.png", 320, 20),
    new BackgroundObject("./img/environment/background/ground_new.png", 320, 20),
    new BackgroundObject("./img/environment/background/foreground2.png", 320, 25),

    new BackgroundObject("./img/environment/background/sky.png", 320 * 2, 0),
    new BackgroundObject("./img/environment/background/background-clouds2.png", 320 * 2, 20),
    new BackgroundObject("./img/environment/background/background-clouds1.png", 320 * 2, 20),
    new BackgroundObject("./img/environment/background/mountains2.png", 320 * 2, 20),
    new BackgroundObject("./img/environment/background/mountains1.png", 320 * 2, 20),
    new BackgroundObject("./img/environment/background/ground2.png", 320 * 2, 20),
    new BackgroundObject("./img/environment/background/ground_new.png", 320 * 2, 20),
    new BackgroundObject("./img/environment/background/foreground2.png", 320 * 2, 25),

    new BackgroundObject("./img/environment/background/sky.png", 320 * 3, 0),
    new BackgroundObject("./img/environment/background/background-clouds2.png", 320 * 3, 20),
    new BackgroundObject("./img/environment/background/background-clouds1.png", 320 * 3, 20),
    new BackgroundObject("./img/environment/background/mountains2.png", 320 * 3, 20),
    new BackgroundObject("./img/environment/background/mountains1.png", 320 * 3, 20),
    new BackgroundObject("./img/environment/background/ground2.png", 320 * 3, 20),
    new BackgroundObject("./img/environment/background/ground_new.png", 320 * 3, 20),
    new BackgroundObject("./img/environment/background/foreground2.png", 320 * 3, 25),

    new BackgroundObject("./img/environment/background/sky.png", 320 * 4, 0),
    new BackgroundObject("./img/environment/background/background-clouds2.png", 320 * 4, 20),
    new BackgroundObject("./img/environment/background/background-clouds1.png", 320 * 3, 20),
    new BackgroundObject("./img/environment/background/mountains2.png", 320 * 4, 20),
    new BackgroundObject("./img/environment/background/mountains1.png", 320 * 4, 20),
    new BackgroundObject("./img/environment/background/ground2.png", 320 * 4, 20),
    new BackgroundObject("./img/environment/background/ground_new.png", 320 * 4, 20),
    new BackgroundObject("./img/environment/background/foreground2.png", 320 * 4, 25),
  ],
  [new Hud()]
);
